services:
  - type: web
    name: dermoai-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false